- name: compile module file
  command: checkmodule -M -m -o /tmp/myapp.mod /tmp/myapp.te

- name: build policy package
  command: semodule_package -o /tmp/myapp.pp -m /tmp/myapp.mod

- name: load policy package
  command: /usr/sbin/semodule -i /tmp/myapp.pp
